### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by arderyp** [bbiw/sqrl#1]
Is this still something you are actively developing and bringing up to speed with the official Version 1 release of SQRL that was just published?

If this is still active, a README would be a helpful first step.

**Comment by lernisto** [comment]
SQRL is an interesting protocol, and I would love to see it implemented and adopted. Unfortunately, I am not able to dedicate the time to develop this right now. I don't remember if this code works at all.

**Comment by lernisto** [comment]
status: inactive. 
If Steve ever publishes a real spec or maybe gets the IEFT interested, I would love to work on it again.
